"""Build incoming_refs.json: for every statute section, the sections whose body
text cites it. Mirrors the citation-detection rules in app.js (linkifyCitations).

Run from inside CT-Statutes/next/:  python build_incoming.py
"""

import glob
import json
import os
import re
from collections import defaultdict

DATA_DIR = os.path.join("..", "data")
OUT_FILE = "incoming_refs.json"

CITATION = re.compile(r"\b(\d{1,3}[a-z]{0,2}-\d+[a-z]{0,3}(?:-\d+[a-z]{0,3})?)\b")
ACT_GUARD = re.compile(r"(P\.A\.|S\.A\.|No\.)\s*$", re.IGNORECASE)
YEAR_GUARD = re.compile(r"\b(19|20)\d{2},?\s*$")
ACT_LIST_GUARD = re.compile(r"^,\s*S\.\s")  # "05-220, S. 2" inside an act list


def title_files():
    return sorted(glob.glob(os.path.join(DATA_DIR, "title_*.json")))


def sections(title):
    for ch in title.get("chapters", []):
        for sec in ch.get("sections", []):
            yield sec


def main():
    files = title_files()
    if not files:
        raise SystemExit(f"No title_*.json found in {DATA_DIR}; run from CT-Statutes/next/")

    # pass 1: the set of real section keys, so bad matches are dropped
    all_keys = set()
    for f in files:
        with open(f, encoding="utf-8") as fh:
            t = json.load(fh)
        for sec in sections(t):
            all_keys.add(sec["section_key"])

    # pass 2: scan body text for cross-citations
    incoming = defaultdict(set)
    for f in files:
        with open(f, encoding="utf-8") as fh:
            t = json.load(fh)
        for sec in sections(t):
            src = sec["section_key"]
            for para in (sec.get("content") or {}).get("body_paragraphs") or []:
                for m in CITATION.finditer(para):
                    key = m.group(1)
                    if key == src or key not in all_keys:
                        continue
                    before = para[max(0, m.start() - 18):m.start()]
                    if ACT_GUARD.search(before) or YEAR_GUARD.search(before):
                        continue
                    if ACT_LIST_GUARD.match(para[m.end():m.end() + 8]):
                        continue
                    incoming[key].add(src)

    out = {
        "note": "target section -> sections whose statute text cites it (generated by build_incoming.py)",
        "targets": {k: sorted(v) for k, v in sorted(incoming.items())},
    }
    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        json.dump(out, fh, separators=(",", ":"))
    pairs = sum(len(v) for v in incoming.values())
    print(f"{len(incoming)} cited sections, {pairs} citation pairs, "
          f"{os.path.getsize(OUT_FILE):,} bytes -> {OUT_FILE}")


if __name__ == "__main__":
    main()
